<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260203224726 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE url (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, original_url VARCHAR(255) NOT NULL, short_code VARCHAR(255) NOT NULL, is_public BOOLEAN NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, clicks INT DEFAULT NULL, session_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F47645AE613FECDF ON url (session_id)');
        $this->addSql('ALTER TABLE url ADD CONSTRAINT FK_F47645AE613FECDF FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE url DROP CONSTRAINT FK_F47645AE613FECDF');
        $this->addSql('DROP TABLE session');
        $this->addSql('DROP TABLE url');
    }
}
